/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.materialrangebar;

import java.util.HashMap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;

import android.app.Activity;
import android.graphics.Color;

// This proxy can be created by calling Materialrangebar.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = MaterialrangebarModule.class)
public class MaterialrangebarProxy extends TiViewProxy {
	private static final String LCAT = "RangeBar 📐";
	private HashMap<String, Integer> colors = new HashMap<String, Integer>();

	public MaterialrangebarProxy() {
		super();
	}

	@Override
	public TiUIView createView(Activity activity) {
		TiUIView view = new MaterialRangeBar(this);
		view.getLayoutParams().autoFillsHeight = true;
		view.getLayoutParams().autoFillsWidth = true;
		return view;
	}

	// Handle creation options
	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);
		String[] colorStrings = { "barColor", "connectingLineColor",
				"pinColor", "textColor", "tickColor", "selectorColor" };
		for (int i = 0; i < colorStrings.length; i++) {
			String color = colorStrings[i];
			if (options.containsKeyAndNotNull(color)) {
				colors.put(color, Color.parseColor(options.getString(color)));
			}
		}
	}

	// Methods
	@Kroll.method
	public void printMessage(String message) {
	}

	@Kroll.getProperty
	@Kroll.method
	public String getMessage() {
		return "Hello World from my module";
	}

	@Kroll.setProperty
	@Kroll.method
	public void setMessage(String message) {
	}
}